=== gutienic/LFRunManager/CORDEXRuns/lisvapRuns/Lisvap_360day/lisflood.dtd
<!-- add this to element that need exact formatting
     if not all lines are collapsed to one line in XML editor
  -->
<!ENTITY % PreserveSpace "xml:space (preserve) #FIXED 'preserve'">

<!-- lisflood the master file
      - sealSpecification
          required
      - metadata?
          optional(?) metadata
      - lfmodule*
          a series of 0 or more (*) lfmodule's
          order of modules is exact as in generated script
  -->
<!ELEMENT lisflood (sealSpecification,metadata?,lfmodule*)>


 <!ELEMENT metadata  (date,author, notes)>
  <!ELEMENT date   (#PCDATA)>
  <!ELEMENT author (#PCDATA)>
  <!ELEMENT notes  (#PCDATA)>
  <!ATTLIST notes   %PreserveSpace;>

<!-- each element defined in sealValueOf/@pattern
     should have this option (#IMPLIED) attribute
  -->
<!ENTITY % EncodedAttr "
          encoding (pcrseal|text) #IMPLIED">

<!-- module that may have an option initial and dynamic element
     has an attribute name that is required and must be unique
  -->
<!ELEMENT lfmodule  (initial?,dynamic?)>
<!ATTLIST lfmodule
           name     ID #REQUIRED>

<!-- element that can have plain text (#PCDATA) interchanged with
     possible lfoption elements
  -->
<!ELEMENT initial   (#PCDATA|lfoption)*>
<!ATTLIST initial
           %PreserveSpace;
           %EncodedAttr;
          >
<!-- like initial -->
<!ELEMENT dynamic   (#PCDATA|lfoption)*>
<!ATTLIST dynamic
           %PreserveSpace;
           %EncodedAttr;
          >
<!-- containing text (script code)
      default
        0 this is NOT the default choice
        1 this is the default choice
      choice
        the identifier to select this option
  -->
<!ELEMENT lfoption  (#PCDATA)>
<!ATTLIST lfoption
             name    CDATA #REQUIRED
             default (0|1) #REQUIRED
             choice  CDATA #REQUIRED
             %EncodedAttr;
             >
<!--
    the "input" file that controls what is extracted from the master file
     lfuser defines textvar's that can be used for substition in the
     lfbinding sections.
    lfbinding contains textvar's that generate pcrcalc binding after
        substitution of the lfuser-textvar's
  -->
<!ELEMENT lfsettings  (lfuser?,lfoptions?,lfbinding?,prolog)>
<!ELEMENT lfuser      (group|textvar)*>
<!ELEMENT lfoptions   (setoption)*>
<!ELEMENT lfbinding   (group|textvar)*>

<!-- prolog MUST contain areamap and timer
  -->
<!ELEMENT prolog      (#PCDATA)>
<!ATTLIST prolog       %PreserveSpace;>

<!-- a group is just a logical grouping of textvar's that have a common
     comment or name
  -->
<!ELEMENT group       (comment,(group|textvar)*)>
<!ATTLIST group
          name        CDATA #IMPLIED>
<!ELEMENT comment     (#PCDATA)>
<!ATTLIST comment     %PreserveSpace;>

<!ELEMENT textvar     (comment?)>
<!ATTLIST textvar
          name        CDATA #REQUIRED
          value       CDATA #REQUIRED>

<!ELEMENT setoption   EMPTY>
<!ATTLIST setoption
          name        CDATA #REQUIRED
          choice      CDATA #REQUIRED>

<!-- PCRaster internals
       such as sealSpecification and its sub-elements
     not of importance to JRC
  -->
<!ENTITY % pcraster SYSTEM "pcraster.dtd">
%pcraster;

=== gutienic/LFRunManager/CORDEXRuns/lisvapRuns/LisvapLinux2013/lisvap.xml
<?xml version="1.0" ?>
<!DOCTYPE lisflood
  SYSTEM 'lisflood.dtd'>
<!-- Lisvap master code, JvdK,24-07-2006 --><lisflood>
<sealSpecification>
 <sealValueOf pattern="initial"/>
 <sealValueOf pattern="dynamic"/>
 <sealValueOf pattern="lfoption"/>
</sealSpecification>
<metadata>

<date>02 May 2013</date>
<author>Peter Burek, Johan van der Knijff</author>

<notes>

#######################################################
#
# ##       ####  ######  ##     ##    ###    ########  
# ##        ##  ##    ## ##     ##   ## ##   ##     ## 
# ##        ##  ##       ##     ##  ##   ##  ##     ## 
# ##        ##   ######  ##     ## ##     ## ########  
# ##        ##        ##  ##   ##  ######### ##        
# ##        ##  ##    ##   ## ##   ##     ## ##        
# ######## ####  ######     ###    ##     ## ##  
# 
#######################################################
#
#   Potential evaporation pre-processor for LISFLOOD water balance and flood model
# 
#    (C) Institute for Environment and Sustainability
#        Joint Research Centre of the European Commission
#        TP261, I-21020 Ispra (Va), Italy
#
# IMPORTANT(1): Lisvap is designed to be run using a DAILY time step. Using other time
# intervals may give unexpected results and therefore doing so is NOT RECOMMENDED!
#
# IMPORTANT (2): it is assumed that all input maps have already been corrected
# for altitude (if necessary). Lisvap script contains no altitude corrections,
# (except for psychrometric constant)
#
# IMPORTANT (3): from WOFOST documentation (http://www.treemail.nl/download/treebook7/weather/chapt4.htm#eq4_26):
#
#   "The calculation of the photoperiodic day length makes no sense when the sun is 
#   continuously at higher inclinations, therefore this calculation method is limited to 
#   -66.5+4 and 66.5-4 degrees of latitude"
#
# ==> prevent any computation outside of this range (will yield negative extra-terrrestrial
# radiation values for high latitudes!!
# ------------------------------------------------------------
#
# # LISVAP02052013.XML   PCR2009W2M007
# fixed Brunt_e=0.2 and Brunt_f=0.9 because with 2 values for each there was clear boundary forming around the 45 lat line in the output

# LISVAP29102012.XML   PCR2009W2M006
# major change with input from Victor Ntegeka
# - net long-wave-radiation calculated now by default with Allen et al. 1994 formular
# - old method by Brunt can be use with option useBrunt = 1
# - removed use of table for Brunt_e Brunt_f as there are only 2 values in
#    and default approach for calculating net long-wave-radiation is Allen et al. 1994
# - Reading Actual vapour pressure maps (pd) and Incoming daily global solar radiation maps (rg) are default
# - if option useRgdMaps = 0  use Hargreaves radiation equation (default:useRgdMaps = 1)
# - if option usePenmanET =  0  use Hargreaves evapotranspiration (default:usePenmanET = 1)
# Lisvap needs at least Pcraster version 2009 


# LISVAP07072011.XML   PCR2007W1M005
# added option useTavg
# - uses avergae tempature instead of min and max Temperature
# - only useful if you use radiantion rn, rg
#
#
# LISVAP0204208.xml
# Differences with respect to lisvap24012008.xml:
# 1. Values of constants Brunt_e and Brunt_f are now defined in a lookup table as a function
#    of latitude (Lat). Requires additional tables TabEBrunt and TabFBrunt
#
# LISVAP24012008.xml
# Differences with respect to lisvap28072006.xml:
#
# All changes with respect to previous version were introduced to correct unintentional MV
# creation at high latitudes:
#
# 1. DayLength eqn: changed 2nd occurrence of tmp1 by tmp2 (doesn't make any difference btw)
# 2. Computation of DayLength resulted in MV at high latitudes. This is now corrected using
#    a cover statement
# 3. Computation of integral solar height resulted in MV and negative values at high latitudes.
#    Added maximize and cover statement to fix this.
# 4. Missing values in sunshine duration at high latitudes are now covered up (MV caused by zero 
#    division in atmospheric transmission equation if Angot radiation equals 0)
#
#
# LISVAP28072006.xml
# Differences with respect to lisvap24072006.xml:
#
# 1. Changed handling of missing values; apparently simply setting a variable to 1e31 doesn't automatically
#    result in mv! Instead, use variable "Nothing". 
#
#
# LISVAP24072006.XML
# 
# based on evapmars09082005.mod + evapera26042004.mod
# 
# "lisvap" new name for LISFLOOD pre-processor to calculate evaporation
#  lisvap uses wrapper similar to LISFLOOD wrapper (same layout applies) 
#
# Differences with respect to evapmars09082005:
#
# 1. Incorporated alternative input (e.g. TDew as substitute for EAct)
# 2. Cloud cover / sunshine hours: it is now possible to exclude one (or both)
#    of these variables
# 3. Re-structured Rgd calculations.
# 4. Standard PCRaster missing value identifier (NoDataFlag) is now used to identify missing values in 
#    meteo input. Makes handling of multiple input variable combinations easier, and makes it easier to detect 
#    if any essential input is missing (in that case there will be "holes" in the output maps). Modify interpolation
#    scripts for this (use "1e31" for mv in sunshine, cloud cover, etc). 
# 
#


</notes>

</metadata>


<lfmodule name="setConstants">
<initial>

Nothing=if(MaskMap eq 0, 1.0);
	# Nonsense statement to create map of only missing values
	# Note that non-mv may occur outside "true" part of MaskMap,
	# but as long as PCRaster's missing value compression is activated
	# (-m switch) nothing is calculated there anyway

ZeroMask=if(MaskMap eq 1, scalar(0));
	# Another nonsense statement to create map of scalar zero values
	# (used to cover up missing values in relative sunshine duration
	# computation)

ZeroKelvin=273.15;
	# Temperature in Kelvin corresponding to 0 degrees Centigrade

Pi=3.14159265358979323846;
	# Numerical value of Pi

MJtoJ=1E6;
	# Conversion factor from [MJ] to [J]

DtDay=DtSec/86400;
	# Time step, expressed as fraction of day 

Cs=Cs*MJtoJ;
Bh=Bh*MJtoJ;
	# Convert Cs and Bh coefficients to [J/m2/d]

<lfoption name="useBrunt" choice="1" default="0" >
Brunt_e=0.2;
Brunt_f=0.9;
# with 2 values there is clear boundary forming around the 45 lat line in the output
# 02 and 0.9 according to V. Ntegeka

#Brunt_e=if(Lat lt 45,0.3,0.1);
#Brunt_f=if(Lat lt 45,0.7,0.9);
	# Brunt constants (net outgoing radiation equation)
	# NOTE: in previous versions the values for Lat > 45
	# were always used (i.e. 0.1 and 0.9, which were hard-coded!) 
</lfoption>

</initial>
</lfmodule>

<lfmodule name="readMeteo">
<dynamic>

# ************************************************************
# ***** READ METEOROLOGICAL DATA *****************************
# ************************************************************

<lfoption name="useTavg" choice="0" default="1" >
TMax=timeinput(TMaxMaps);
	# Maximum temperature [deg C or K]

TMin=timeinput(TMinMaps);
	# Minimum temperature [deg C or K]


</lfoption>

<lfoption name="useTavg" choice="1" default="0" >
TAvg=timeinput(TAvgMaps);
DeltaT=scalar(0);
	# average temperature [deg C or K]
</lfoption>

<lfoption name="usePenmanET" choice="1" default="1">
 <lfoption name="useEActMaps" choice="1" default="1" >
 EAct=timeinput(EActMaps);
	# Actual vapour pressure [mbar]
 </lfoption>

 <lfoption name="useEActMaps" choice="0" default="0" >
 EAct=Nothing;
	# Flag to indicate missing Actual vapour pressure [mbar]
 </lfoption>

 <lfoption name="useTDewMaps" choice="1" default="0" >
 TDew=timeinput(TDewMaps);
 	# Dewpoint temperature [deg C]
 </lfoption>

 <lfoption name="useTDewMaps" choice="0" default="1" >
 TDew=Nothing;
	# Flag to indicate missing dewpoint temperature
 </lfoption>

 <lfoption name="useWindMaps" choice="1" default="1" >
 Wind=timeinput(WindMaps);
	# Windspeed at 10 m altitude [m/s]
 </lfoption>

 <lfoption name="useWindMaps" choice="0" default="0" >
 Wind=Nothing;
	# Flag to indicate missing windspeed
 </lfoption>

 <lfoption name="useWindUVMaps" choice="1" default="0" >
 WindV=timeinput(WindVMaps);
 WindU=timeinput(WindUMaps);
	# V- and U windspeed components at 10 m altitude [m/s]
 </lfoption>

 <lfoption name="useWindUVMaps" choice="0" default="1" >
 WindV=Nothing;
 WindU=Nothing;
	# Flag to indicate missing V and U components
 </lfoption>


 <lfoption name="useSunMaps" choice="1" default="0" >
 SunshineHour=timeinput(SunMaps);
	# Number of daily bright sunshine hours  [hours]
 </lfoption>

 <lfoption name="useSunMaps" choice="0" default="1" >
 SunshineHour=Nothing;
	# Flag to indicate missing sunshine duration
 </lfoption>

 <lfoption name="useCloudMaps" choice="1" default="0" >
 CloudCover=timeinput(CloudMaps);
	# Cloud cover [octas]
 </lfoption>

 <lfoption name="useCloudMaps" choice="0" default="1" >
 CloudCover=Nothing;
 	# Flag to indicate missing cloud cover
 </lfoption>
</lfoption>

<lfoption name="usePenmanET" choice="0" default="0">
 SunshineHour=Nothing;
 CloudCover=Nothing;
</lfoption>

<lfoption name="useRgdMaps" choice="1" default="1" >
# Following statements allow for the use of pre-calculated values
# of incoming solar radiation and net longwave radiation, respectively
# (resp. SSRD and STR in ERA40). 

Rgd=timeinput(RgdMaps);
	# Incoming (downward surface) solar radiation [J/m2/d] (SSRD variable in ERA40)
</lfoption>

<lfoption name="useRgdMaps" choice="0" default="0" >
Rgd=Nothing;
	# Incoming (downward surface) solar radiation [J/m2/d] (SSRD variable in ERA40)
</lfoption>


<lfoption name="useRNMaps" choice="1" default="0" >
RN=(timeinput(RNMaps))*-1;
	# Net longwave radiation [J/m2/d] (STR variable in ERA40) 
	# Value of RN always *negative* (because net radiation flux is 
	#   outgoing, i.e. from soil surface to atmosphere). Converted to
	#   positive value here for consistency with original MARS version)

</lfoption>


</dynamic>
</lfmodule>

<lfmodule name="prepatoryCalculations">
<dynamic>

# ************************************************************
# ***** PREPATORY CALCULATIONS********************************
